### ISSUE TITLE
Cannot archive Project if using New (2017) Xcode build system

### ISSUE THREAD

**Issue by DimDL** [Alfresco/alfresco-ios-app#1073]
I cannot archive Project if using the new, (2017), default Xcode build system. Using the legacy one (Xcode > File > Workspace Settings > Use Legacy Build System) works, for now, as a temporary workaround. New build system leads to 2x speedup in build time, among other features !

**Comment by emanuellupu** [comment]
Hi Dimitri, this is a known issue and will be handled in a future release. For now, indeed, please use the legacy build system. I'll leave the ticket opened for transparency until this issue will be resolved. Thanks

**Comment by emanuellupu** [comment]
Hi Dimitri, we addressed this issue and it should be resolved. Currently the change lives on https://github.com/Alfresco/alfresco-ios-app/tree/MOBILEAPPS-6 branch for the app. The SDK change which was generating this issue has been merged to master for the corresponding git submodule.  I'm going to close this ticket but feel free to reopen if you encounter any issues.
