### ISSUE TITLE
Icons missing in iPad version

### ISSUE THREAD

**Issue by epm157** [Alfresco/alfresco-ios-app#474]
Some of file details tabs icons are missing when I run the alfresco iOS application on iPad simulator unlike running it on iPhone emulator as you can see in the photos.
I am running alfresco iOS app on Xcode simulator so I am not sure wether in actual device this happens.

iPad simulator screenshot:
![ios simulator screen shot 05 may 2015 09 20 30](https://cloud.githubusercontent.com/assets/4679569/7468427/b48b801c-f308-11e4-95c4-989c75488c85.png)
iPhone simulator screenshot:
![ios simulator screen shot 05 may 2015 09 22 54](https://cloud.githubusercontent.com/assets/4679569/7468428/b499c12c-f308-11e4-9381-177bf0d7edd2.png)

**Comment by mikeh** [comment]
That looks like the view isn't swapping into iPad mode to me. Can you give me more details about which version of our code you're using, as well as the Xcode version and Simulator type please?

**Comment by epm157** [comment]
Simulator version is 8.3 and Xcode is 6.3.1 and I am building the app using 2.0.2 tag.
If it runs correctly on actual iPad it is fine for me :)

**Comment by mikeh** [comment]
OK, that's it then. Apple changed the definition of `UI_USER_INTERFACE_IDIOM` in Xcode 6.3 and that broke some preprocessor logic we had in the app. See commit 5c4d5778eec2127f5b23755e26dc8c25c7b22025 for details on the fix.
