### ISSUE TITLE
Can not search into document content

### ISSUE THREAD

**Issue by slaptot** [Alfresco/alfresco-ios-app#510]
iOS app is not able to search into content and release notes in app store talk about it: "Option to search on full content text". Why can not search content? Is it correct?
Android app is working fine and search into content properly.

Thanks in advance,
Alberto

**Comment by tmughal** [comment]
Hi Alberto,

By default, this functionality is not turned on. In the app settings, toggle the switch ["Full Content Search"](http://docs.alfresco.com/ios/references/ios-mobile-settings.html#mobile-settings__4) to on, this should allow you to carry out content depth searches.

Regards,
Taz

**Comment by slaptot** [comment]
Thanks! So newbie on Alfresco :(
