### ISSUE TITLE
Write new code in Swift

### ISSUE THREAD

**Issue by bhagyas** [Alfresco/alfresco-ios-app#660]
To enable better contributions and code quality.

Also existing code can be migrated as required basis.

**Comment by mikeh** [comment]
In line with many projects, we will likely start developing some new features in Swift but this will be decided on a case-by-case basis. I am aware that large projects such as Firefox and Outlook are having success with the language, but their development teams are significantly larger.

Whilst there are currently no plans to perform a full migration of the codebase, we are keeping a careful eye on Swift's ongoing development and will be more likely to adopt the language once it becomes more stable in v3.0.

We are always willing to receive contributions, in either Objective-C or Swift.

References:
- [It's Coming: the Great Swift API Transformation](https://swift.org/blog/swift-api-transformation/)
- [Ben Sandofsky: Is It Time for Swift?](https://realm.io/news/ben-sandofsky-time-for-swift/)
- [Hacker News discussion of: Is It Time for Swift?](https://news.ycombinator.com/item?id=11004659)

**Comment by parthh3008** [comment]
@mikeh When alfresco app SDK will release in Swift?
