### ISSUE TITLE
I can't use favorites in offline mode

### ISSUE THREAD

**Issue by cblaha** [Alfresco/alfresco-ios-app#909]
When I mark a document as favorite and turn then my iphone in offline mode, i get only a rotating circle when i while access the document.

**Comment by SilviuOdobescu** [comment]
Hi cblaha,
I am assuming that you are using version 2.4 or 2.5 of the app. In version 2.4 a new "Sync" action was introduced to enable users to select content to be available offline, leaving the "Favorite" system to be a online only feature. Please have a look at the documentation available at http://docs.alfresco.com/ios/concepts/mobile-synced-content.html
