### ISSUE TITLE
Sync folder with subsolder won't work

### ISSUE THREAD

**Issue by cblaha** [Alfresco/alfresco-ios-app#916]
When I mark a folder in a site for sync, the alfresco app will not sync all files and folders.

The foldersize that i will sync is about 400MB.

**Comment by sky4055** [comment]
Thanks cblaha, samie issue here.

**Comment by john-knowles** [comment]
Thank you for the feedback.  We will resolve this in the next release.

**Comment by SilviuOdobescu** [comment]
Version 2.6 of the app launched containing a fix for this bug.

**Comment by sky4055** [comment]
I tested and confirmed. Thank you!

**Comment by john-knowles** [comment]
Thank you for letting us know.
