### ISSUE TITLE
Problem on connection to on premises repository

### ISSUE THREAD

**Issue by rhuanbarreto** [Alfresco/alfresco-ios-app#990]
My Alfresco is behind a reverse proxy (nginX) and I'm having problems on connecting to the repository.

I always get the error on diagnostic: "Checking Repository Connection".

On the nginx logs, I can see that the app is calling the following requests during the diagnostic.

`GET /alfresco/service/api/server` - That's OK 
`GET /alfresco/api/-default-/public/cmis/versions/1.0/atom`- That's OK
`GET /-default-/public/cmis/versions/1.0/atom/id?id=c7523685-30b6-4d43-90a2-d7c6badecbba&filter=&includeAllowableActions=true&includeACL=false&includePolicyIds=false&includeRelationships=none&renditionFilter=` - Here I get an 404

But the last one should be wrong once the base URL is /alfresco/api/

Why the app is putting this request?

**Comment by john-knowles** [comment]
@rhuanbarreto please can you refer to the [documentation](https://docs.alfresco.com/6.0/tasks/configure-ssl-prod.html) for Configuring SSL, in particular pay attention to the alfresco-global.properties values mentioned in section 5.

**Comment by emanuellupu** [comment]
Closing the issue. @rhuanbarreto, fell free to reopen the issue if you feel there's another cause for your connectivity problem.
